# Generated by Django 3.0.11 on 2021-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='estatus_habitacion',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20, verbose_name='Estatus actual de la habitacion'),
        ),
    ]
