# Generated by Django 3.0.11 on 2021-01-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_habitaciones_estatus_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='tipo_habitacion',
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='tipo_habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.TipoHabitacion', verbose_name='Tipo de habitacion'),
        ),
    ]
