# Generated by Django 3.0.11 on 2021-01-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_de_reserva', models.BooleanField(default=False, verbose_name='¿Es la persona responsable de la reserva?')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('documento_identidad', models.CharField(blank=True, help_text='Puede incluir cualquier documento de identidad (DNI, TIE, NIE, PASAPORTE).', max_length=50, null=True, verbose_name='Documento de identidad')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Reservante',
                'verbose_name_plural': 'Reservantes',
            },
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='telefono',
        ),
        migrations.AddField(
            model_name='reservas',
            name='reservantes',
            field=models.ManyToManyField(blank=True, to='bookings.Reservantes', verbose_name='Personas incluidas en esta reserva'),
        ),
    ]
