# Generated by Django 3.0.11 on 2021-01-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210111_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='reservantes',
        ),
        migrations.AddField(
            model_name='reservantes',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservas', verbose_name='Reserva'),
        ),
    ]
